### ISSUE TITLE
Add Abilities data

### ISSUE THREAD

**Issue by krisling049** [krisling049/warcry_data#16]
Add a json for abilities. 
Starting point can be scraping the battlescribe data. 
Schema TBD.

**Comment by mpost** [comment]
I have scraped all the abilities for the factions from bsdata. Maybe this could a starting point for you: https://github.com/mpost/warcry-data

**Comment by krisling049** [comment]
> I have scraped all the abilities for the factions from bsdata. Maybe this could a starting point for you: https://github.com/mpost/warcry-data

Great, that cuts down a lot of work, thank you :)

**Comment by apathyward** [comment]
I can't view this repo but it's incredibly useful to have a Separate field for the ability name

**Comment by krisling049** [comment]
We've got abilities in now. Going to close this and we can move into correctness-checking mode for abilities.
