### ISSUE TITLE
Mismatching fighter names compared to bsdata

### ISSUE THREAD

**Issue by mpost** [krisling049/warcry_data#21]
When extracting the fighter names from bsdata and matching them against the names in the fighters.json the following names do not have direct matches. Instead i performed a fuzzy search (using fuse.js) to find the closest match. 105 items do not match directly. When ignoring casing, 67 fighter names are mismatched.

Interestingly the errors are on both sides with an advantage to warcry_data. Below you find the two tables.

### Fighter names with direct matches (with casing)

| BSData |warcry_data| score|
| ------------- | ------------- |------|
| Skryke | Shryke | 0.408248290463863
| Askurgan Aesthetic with Howling Glaive | Askurgan Ascetic with Howling Glaive | 0.5891631564934728
| Valreek, The Tracker | Valreek The Tracker | 0.42135955457496554
| Sister of Slaughter with Kruiplash and Sacrifical Knife | Sister of Slaughter with Kruiplash and Sacrificial Knife | 0.48164543787776865
| Thrialla the Lash | Thrialla, the Lash | 0.4415861932646291
| Traxyaa, The Aegis | Traxyaa, the Aegis | 0.000030475301089508962
| Orruk Brute with Pair of Brute Choppas | Orruk Brute with pair of Brute Choppas | 0.0011002140903293744
| The Briar Queen | Briar Queen | 0.6267292251549516
| Wollop Da Skul | Wollop da Skul | 0.000030475301089508962
| Shroommancer | Shroomancer | 0.28867513459481287
| Prog da Netter | Prog Da Netter | 0.000030475301089508962
| Auric Runeson with Ancestral War-axe | Auric Runeson with Ancestral War-Axe | 0.0003172702789197851
| Hedkrakka, Gob of Gork | Hedkrakka,  Gob of Gork | 0.4617366309441026
| Gore-Grunta Boss with Jagged Gore-hacka | Gore-grunta Boss with Jagged Gore-hacka | 0.0003172702789197851
| Witch Aelf with Sciansa and Bladed Buckler | Witch Aelf with Sciansá and Bladed Buckler | 0.5194295516488322
| Witch Aelf with Paired Sciansa | Witch Aelf with Paired Sciansá | 0.4675880457636936
| Askurgan Acolyte with Throat-taker | Askurgan Acolyte with Throat-Taker | 0.0001220703125
| Knight Of Shrouds on Ethereal Steed | Knight of Shrouds on Ethereal Steed | 0.0006407281516562312
| Bloated One with Raker-claw and Hooked Net | Bloated one with Raker-claw and Hooked Net | 0.0011002140903293744
| Clearblood Clearblood | Clearblood | 0.7237468644557459
| Heart-eater | Heart-Eater | 1.4901161193847656e-8
| Kalexis the Silvered Blur | Kalexis the Silverered Blur | 0.5318295896944989
| Askurgan Aesthetic with Charnel Mace | Askurgan Ascetic with Charnel Mace | 0.5891631564934728
| Knight Of Shrouds | Knight of Shrouds | 0.000030475301089508962
| Retaria, The Entangler | Retaria the Entangler | 0.40993127807090113
| Endrinmaster with Endringharness | Endrinmaster with Endrinharness | 0.367929178906404
| Korsh "The Sneak" | Korsh 'the Sneak' | 0.5393400113261941
| Bullgor with Bullgor Axe and Bullshield | Bloodkine with Bullgor Axe and Bullshield | 0.6588969147804601
| Gaunt Summoner of Tzeentch on Disc | Gaunt Summoner of Tzeentch | 0.6838911999336903
| Kairic Acolytes with Paired Cursed Blades | Kairic Acolyte with Paired Cursed Blades | 0.4931163522466796
| Blood Whelp with Barb-spear | Blood Whelp with Barb-Spear | 0.0001220703125
| Desecrator with Statue-smasher Hammer | Desecrator with Statue-Smasher Hammer | 0.0001220703125
| Mournfang Pack with Gargant Hacker | Mournfang Rider with Gargant Hacker | 0.6604178086455843
| Gaunt Summoner of Tzeentch on Foot | Gaunt Summoner of Tzeentch | 0.6838911999336903
| Dead-Eye Lund | Dead-eye Lund | 0.0000029272958679216153
| Murghoth Half-horn | Murghoth Half-Horn | 0.0000029272958679216153
| Enlightened Aviarch on Foot | Enlightened Aviarch | 0.650511861247643
| Kairic Acolytes with Cursed Glaive and Arcanite Shield | Kairic Acolyte with Cursed Glaive and Arcanite Shield | 0.503092369594549
| Kairic Acolytes with Cursed Blade and Arcanite Shield | Kairic Acolyte with Cursed Blade and Arcanite Shield | 0.503092369594549
| Orruk Brute with Gore-choppa | Orruk Brute with Gore-Choppa | 0.0001220703125
| Orruk Gore-Grunta with Jagged Gore-hacka | Orruk Gore-Grunta with Jagged Gore-Hacka | 0.0003172702789197851
| Gor with Paired Gor Blades | Gor with Pair of Gor Blades | 0.643692090942401
| Kairic Acolytes with Scroll of the Dark Arts | Kairic Acolyte with Scroll of Dark Arts | 0.6581964180125326
| Stormfiend with Warpfire Projectors | Stormfiend with Warpfire projectors | 0.0001220703125
| Stormfiend with Doomflayer Gauntlets | Stormfiend with Doomflayer gauntlets | 0.0001220703125
| Paladin | Paladin with Starsoul Mace | 0.17782794100389226
| Tzaangor Enlightened on Foot | Tzaangor Enlightened | 0.6422024326348383
| Brimstone Horror | Brimstone Horrors | 0.08699614330652679
| Gryph-hound | Gryph-Hound | 1.4901161193847656e-8
| Centaurion Marshal | Centaurian Marshal | 0.35996574083187666
| Cabalist with Dagger | Cabalist with Familiar | 0.6703562957901678
| Blood Whelp with Claw-flail | Blood Whelp with Claw-Flail | 0.0001220703125
| Chaos Warrior with Chaos Halberd and Runeshield | Chaos Warrior with Chaos Halberd and Chaos Runeshield | 0.6583362972852207
| Lord-Celestant | Lord- Celestant | 0.3934085002888523
| Magister on Foot | Magister | 0.7071067811865476
| Kairic Acolytes with Vulcharc | Kairic Acolyte with Vulcharc | 0.43092381945890607
| Sepsimus Plaguesworn | Sepsimus the Plaguesworn | 0.6285605986265814
| Lord Of Plagues | Lord of Plagues | 0.000030475301089508962
| Lord Of Blights | Lord of Blights | 0.000030475301089508962
| K'charik | K'Charik | 1.4901161193847656e-8
| Tzaangor Enlightened on Disc | Tzaangor Enlightened on Disc of Tzeentch | 0.2443430552693972
| Grib da Wonky Lance | Grib Da Wonky Lance | 0.0001220703125
| Pokin Snark | Pokin' Snark | 0.42841797667275966
| Ennias Curse-born | Ennias Curse-Born | 0.0000029272958679216153
| Helmar the Hewer | Helmwar the Hewer | 0.4493775633055149
| Petitioner with Sword and Shield | Petitioner with Sword and shield | 0.0003172702789197851
| Stormfiend with Ratling Cannons | Stormfiend with Ratling cannons | 0.0001220703125
| The Lurking Skaven | Lurking Skaven | 0.5876102683538874
| The Hungering Skaven | Hungering Skaven | 0.5661273069982156
| Stormvermin and Clanshield | Stormvermin with Rusty Halberd | 0.8408964152537146
| The Festering Skaven | Festering Skaven | 0.5661273069982156
| Plague Monk with Woe-stave and Foetid Blade | Plague Monk with Pair of Foetid Blades | 0.8172404826132724
| Chaos Marauder Horseman with Javelin and Shield | Chaos Marauder Horseman with Marauder Flail | 0.7536674547791905
| Chaos Marauder Horseman with Axe and Shield | Chaos Marauder Horseman with Marauder Flail | 0.7334143524711784
| Varanguard with Ensorcelled Weapon | Varanguard with Ensorcelled weapon | 0.0001220703125
| Chaos Warrior with Chaos Hand Weapon and Runeshield | Chaos Warrior with Chaos Hand Weapon and Chaos Runeshield | 0.6748664622622054
| Elathain Ill-Fated | Elathain Ill-fated | 0.0000029272958679216153
| Gutrippa with Wicked Hakka | Gutrippa with Wicked Hacka | 0.4428500142691474
| Mannok da Kunnin' | Mannok Da Kunnin' | 0.000030475301089508962
| Murknob with Belcha-Banna | Murknob with Belcha-banna | 0.000030475301089508962
| Slaughtershade with Umbral Spear | Slaughtershade with Umbral Spears | 0.17782794100389226
| Ailenn, The Mind's Edge | Ailenn the Mind's Edge | 0.4566337854967312
| Mournfang Pack with Culling Club and Ironfist | Mournfang Rider with Culling Club and Ironfist | 0.6456059328416885
| Contorted Epitome | The Contorted Epitome | 0.39508842614580647
| Almeric Eagle-Eye | Almeric Eagle-eye | 0.0000029272958679216153
| Vanguard-Pallador with Shock Hand-axe | Vanguard Pallador with Shock Hand-Axe | 0.4608917983482268
| Gryph-hound | Gryph-Hound | 1.4901161193847656e-8
| Vanguard-Pallador with Starstrike Javelin | Vanguard Pallador with Starstrike Javelin | 0.39753574792558455
| Raptor-Prime with Longstrike Crossbow | Raptor-Prime with Longstrike Bow | 0.5750816584478015
| Skeleton Warrior with Ancient Blade | Skeleton with Ancient Blade | 0.7071067811865475
| Skeleton Warrior with Ancient Spear | Skeleton with Ancient Spear | 0.7071067811865475
| Sir Jedran Falseborn | Sir Jedan Falseborn | 0.42135955457496554
| Vellas von Faine | Vellas Von Faine | 0.000030475301089508962
| Thain, Fourth-and-Last | Thain Fourth-and-Last | 0.3353154638050629
| Evocator on Dracoline with Tempest Blade and Stormstave | Evocator-Prime with Tempest Blade and Stormstave | 0.7135866138716614
| Evocator-Prime on Celestial Dracoline with Tempest Blade and Stormstave | Evocator-Prime on Celestial Dracoline with Tempest Blade and Stave | 0.6308101193913895
| Sequitor with Stormsmite Maul and Stormshield | Sequitor with Storsmite Maul and Soulshield | 0.5944689369871463
| Evocator on Dracoline with Grandstave | Evocator-Prime with Grandstave | 0.7149311685896549
| Sequitor with Tempest Blade and Stormshield | Sequitor with Tempest Blade and Soulshield | 0.5367994244145963
| Sequitor-Prime with Stormspite Maul and Soulshield | Sequitor-Prime with Stormsmite Maul and Soulshield | 0.4931163522466796
| Gryph-hound | Gryph-Hound | 1.4901161193847656e-8
| Skink Alpha Moonstone Club and Star-buckler | Skink with Moonstone Club and Star-buckler | 0.5770028651172843
| Saurus Scar-veteran on Cold One | Saurus Scar-Veteran on Cold One | 0.0003172702789197851
| Skink Alpha Boltspitter and Moonstone Club | Skink with Boltspitter and Moonstone Club | 0.5944689369871463
| Gryph-hound | Gryph-Hound | 1.4901161193847656e-8

### Fighter names with direct matches (ignoring casing)

| BSData |warcry_data| score|
| ------------- | ------------- |------|
| Skryke | Shryke | 0.408248290463863
| Askurgan Aesthetic with Howling Glaive | Askurgan Ascetic with Howling Glaive | 0.5891631564934728
| Valreek, The Tracker | Valreek The Tracker | 0.42135955457496554
| Sister of Slaughter with Kruiplash and Sacrifical Knife | Sister of Slaughter with Kruiplash and Sacrificial Knife | 0.48164543787776865
| Thrialla the Lash | Thrialla, the Lash | 0.4415861932646291
| The Briar Queen | Briar Queen | 0.6267292251549516
| Shroommancer | Shroomancer | 0.28867513459481287
| Hedkrakka, Gob of Gork | Hedkrakka,  Gob of Gork | 0.4617366309441026
| Witch Aelf with Sciansa and Bladed Buckler | Witch Aelf with Sciansá and Bladed Buckler | 0.5194295516488322
| Witch Aelf with Paired Sciansa | Witch Aelf with Paired Sciansá | 0.4675880457636936
| Clearblood Clearblood | Clearblood | 0.7237468644557459
| Kalexis the Silvered Blur | Kalexis the Silverered Blur | 0.5318295896944989
| Askurgan Aesthetic with Charnel Mace | Askurgan Ascetic with Charnel Mace | 0.5891631564934728
| Retaria, The Entangler | Retaria the Entangler | 0.40993127807090113
| Endrinmaster with Endringharness | Endrinmaster with Endrinharness | 0.367929178906404
| Korsh "The Sneak" | Korsh 'the Sneak' | 0.5393400113261941
| Bullgor with Bullgor Axe and Bullshield | Bloodkine with Bullgor Axe and Bullshield | 0.6588969147804601
| Gaunt Summoner of Tzeentch on Disc | Gaunt Summoner of Tzeentch | 0.6838911999336903
| Kairic Acolytes with Paired Cursed Blades | Kairic Acolyte with Paired Cursed Blades | 0.4931163522466796
| Mournfang Pack with Gargant Hacker | Mournfang Rider with Gargant Hacker | 0.6604178086455843
| Gaunt Summoner of Tzeentch on Foot | Gaunt Summoner of Tzeentch | 0.6838911999336903
| Enlightened Aviarch on Foot | Enlightened Aviarch | 0.650511861247643
| Kairic Acolytes with Cursed Glaive and Arcanite Shield | Kairic Acolyte with Cursed Glaive and Arcanite Shield | 0.503092369594549
| Kairic Acolytes with Cursed Blade and Arcanite Shield | Kairic Acolyte with Cursed Blade and Arcanite Shield | 0.503092369594549
| Gor with Paired Gor Blades | Gor with Pair of Gor Blades | 0.643692090942401
| Kairic Acolytes with Scroll of the Dark Arts | Kairic Acolyte with Scroll of Dark Arts | 0.6581964180125326
| Paladin | Paladin with Starsoul Mace | 0.17782794100389226
| Tzaangor Enlightened on Foot | Tzaangor Enlightened | 0.6422024326348383
| Brimstone Horror | Brimstone Horrors | 0.08699614330652679
| Centaurion Marshal | Centaurian Marshal | 0.35996574083187666
| Cabalist with Dagger | Cabalist with Familiar | 0.6703562957901678
| Chaos Warrior with Chaos Halberd and Runeshield | Chaos Warrior with Chaos Halberd and Chaos Runeshield | 0.6583362972852207
| Lord-Celestant | Lord- Celestant | 0.3934085002888523
| Magister on Foot | Magister | 0.7071067811865476
| Kairic Acolytes with Vulcharc | Kairic Acolyte with Vulcharc | 0.43092381945890607
| Sepsimus Plaguesworn | Sepsimus the Plaguesworn | 0.6285605986265814
| Tzaangor Enlightened on Disc | Tzaangor Enlightened on Disc of Tzeentch | 0.2443430552693972
| Pokin Snark | Pokin' Snark | 0.42841797667275966
| Helmar the Hewer | Helmwar the Hewer | 0.4493775633055149
| The Lurking Skaven | Lurking Skaven | 0.5876102683538874
| The Hungering Skaven | Hungering Skaven | 0.5661273069982156
| Stormvermin and Clanshield | Stormvermin with Rusty Halberd | 0.8408964152537146
| The Festering Skaven | Festering Skaven | 0.5661273069982156
| Plague Monk with Woe-stave and Foetid Blade | Plague Monk with Pair of Foetid Blades | 0.8172404826132724
| Chaos Marauder Horseman with Javelin and Shield | Chaos Marauder Horseman with Marauder Flail | 0.7536674547791905
| Chaos Marauder Horseman with Axe and Shield | Chaos Marauder Horseman with Marauder Flail | 0.7334143524711784
| Chaos Warrior with Chaos Hand Weapon and Runeshield | Chaos Warrior with Chaos Hand Weapon and Chaos Runeshield | 0.6748664622622054
| Gutrippa with Wicked Hakka | Gutrippa with Wicked Hacka | 0.4428500142691474
| Slaughtershade with Umbral Spear | Slaughtershade with Umbral Spears | 0.17782794100389226
| Ailenn, The Mind's Edge | Ailenn the Mind's Edge | 0.4566337854967312
| Mournfang Pack with Culling Club and Ironfist | Mournfang Rider with Culling Club and Ironfist | 0.6456059328416885
| Contorted Epitome | The Contorted Epitome | 0.39508842614580647
| Vanguard-Pallador with Shock Hand-axe | Vanguard Pallador with Shock Hand-Axe | 0.4608917983482268
| Vanguard-Pallador with Starstrike Javelin | Vanguard Pallador with Starstrike Javelin | 0.39753574792558455
| Raptor-Prime with Longstrike Crossbow | Raptor-Prime with Longstrike Bow | 0.5750816584478015
| Skeleton Warrior with Ancient Blade | Skeleton with Ancient Blade | 0.7071067811865475
| Skeleton Warrior with Ancient Spear | Skeleton with Ancient Spear | 0.7071067811865475
| Sir Jedran Falseborn | Sir Jedan Falseborn | 0.42135955457496554
| Thain, Fourth-and-Last | Thain Fourth-and-Last | 0.3353154638050629
| Evocator on Dracoline with Tempest Blade and Stormstave | Evocator-Prime with Tempest Blade and Stormstave | 0.7135866138716614
| Evocator-Prime on Celestial Dracoline with Tempest Blade and Stormstave | Evocator-Prime on Celestial Dracoline with Tempest Blade and Stave | 0.6308101193913895
| Sequitor with Stormsmite Maul and Stormshield | Sequitor with Storsmite Maul and Soulshield | 0.5944689369871463
| Evocator on Dracoline with Grandstave | Evocator-Prime with Grandstave | 0.7149311685896549
| Sequitor with Tempest Blade and Stormshield | Sequitor with Tempest Blade and Soulshield | 0.5367994244145963
| Sequitor-Prime with Stormspite Maul and Soulshield | Sequitor-Prime with Stormsmite Maul and Soulshield | 0.4931163522466796
| Skink Alpha Moonstone Club and Star-buckler | Skink with Moonstone Club and Star-buckler | 0.5770028651172843
| Skink Alpha Boltspitter and Moonstone Club | Skink with Boltspitter and Moonstone Club | 0.5944689369871463

**Comment by krisling049** [comment]
Thanks for the report! I agree we'll need to go through and check these by eye. We've discussed casing over discord.

**Comment by apathyward** [comment]
we decided to keep the commas. to prioritize Compendium & White dwarf spelling and punctuation. we didn't actually decide anything definite about casing except that small errors are big for some usages but tiny for others.

every entry should match exactly with that entry's name in the compendium/white dwarf
