### ISSUE TITLE
Field name "warband" should be named "faction"

### ISSUE THREAD

**Issue by mpost** [krisling049/warcry_data#27]
A fighter profile currently has the field `'warband'` which should in fact be labelled `'faction'`.

According to the core rules:

> When you pick your warband, you must first pick a faction. Below is a list of all the factions currently in Warcry. Each fighter in Warcry belongs to one of these factions, as denoted by the faction runemark on their profile.

So a warband is created from multiple fighters which can come from multiple factions.

**Comment by krisling049** [comment]
I agree it would be more correct to use 'faction' instead of 'warband'. However, I don't feel there's a strong enough reason for a schema change at this time.
