### ISSUE TITLE
Mark deprecated factions

### ISSUE THREAD

**Issue by troelskn** [krisling049/warcry_data#57]
There is currently both the old CoS and the new factions. Which is fine for historical reasons, but it would be nice if the old faction was marked as deprecated. Since we don't have a "faction/warband" data type, I suggest adding a field on the fighter for this. Just a boolean `deprecated: true`.

**Comment by apathyward** [comment]
I second this: I'm having issues in TTS due to there being two entries named Flagellant, Prophet, Hammerer, Longbeard, etc.

**Comment by krisling049** [comment]
Following our chat over discord, the old Cities of Sigmar profiles have been removed from the data.

They can be recovered via git history if ever needed in future.
