### ISSUE TITLE
fighters.json data issues

### ISSUE THREAD

**Issue by barrysheppard** [krisling049/warcry_data#6]
Warband names of
Maggotkin Of Nurgle Daemons
Maggotkin Of Nurgle Rotbringers
should have lower case of

Black Ark Cosair should be Black Ark Corsair

Chimera (and others) have wrong weapon range, should be 0 min and 2 max. Order for ranges is reversed which might be causing the confusion, sorry! XD

**Comment by servo-scribe** [comment]
I'll jump on this now 👍

**Comment by tiltos** [comment]
PR up

**Comment by krisling049** [comment]
PR merged, closing issue. Thanks for the quick fix @tiltos and thanks for the report @barrysheppard!
