### ISSUE TITLE
Typos - go home you're drunk

### ISSUE THREAD

**Issue by theironmonkey** [krisling049/warcry_data#81]
https://github.com/krisling049/warcry_data/blob/f3d5b1ce66fe44a6d30de0557867260802159850/data/abilities.json#L3102
https://github.com/krisling049/warcry_data/blob/f3d5b1ce66fe44a6d30de0557867260802159850/data/abilities.json#L4292
https://github.com/krisling049/warcry_data/blob/f3d5b1ce66fe44a6d30de0557867260802159850/data/abilities.json#L7262
https://github.com/krisling049/warcry_data/blob/f3d5b1ce66fe44a6d30de0557867260802159850/data/abilities.json#L7280

All reference "pints" instead of points.

**Comment by troelskn** [comment]
Also: "the ycannot"
